# Generated by Django 4.2.3 on 2023-07-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cust', models.CharField(max_length=255)),
                ('mail_cust', models.TextField(blank=True)),
                ('phone_cust', models.TextField(max_length=15)),
                ('password_cust', models.TextField(max_length=255)),
                ('photo_cust', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
