# Generated by Django 4.2.3 on 2023-07-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custnote',
            name='cust_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='textlist.customer', unique=True),
        ),
        migrations.AlterField(
            model_name='custnote',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='textlist.note', unique=True),
        ),
    ]
