# Generated by Django 4.2.3 on 2023-07-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_cust',
            field=models.TextField(blank=True, max_length=15),
        ),
    ]
