# Generated by Django 4.2.3 on 2023-07-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textlist', '0002_alter_custnote_cust_note_alter_custnote_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custnote',
            name='cust_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='textlist.customer'),
        ),
    ]
