# Generated by Django 4.2.3 on 2023-07-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textlist', '0002_alter_customer_phone_cust'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_note', models.TextField(blank=True, max_length=255)),
                ('time_note', models.DateField()),
                ('text_note', models.TextField(blank=True, max_length=1000)),
                ('telegram_send', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CustNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='textlist.customer')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='textlist.note')),
            ],
        ),
    ]
