# Generated by Django 4.2.3 on 2023-07-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textlist', '0003_note_custnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo_cust',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
