# Generated by Django 4.2.3 on 2023-07-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textlist', '0003_alter_custnote_cust_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name_cust', 'time_create'], 'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['title_note', 'time_note'], 'verbose_name': 'Нотатка', 'verbose_name_plural': 'Нотатки'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='mail_cust',
            field=models.TextField(blank=True, verbose_name='Пошта користувача'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_cust',
            field=models.CharField(max_length=255, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password_cust',
            field=models.TextField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_cust',
            field=models.TextField(blank=True, max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата та час створення акаунту'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее редактирование'),
        ),
    ]
