# Generated by Django 4.2.3 on 2023-07-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textlist', '0004_alter_customer_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mail_cust',
            field=models.TextField(blank=True, unique=True, verbose_name='Пошта користувача'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_cust',
            field=models.CharField(max_length=255, unique=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_cust',
            field=models.TextField(blank=True, max_length=15, unique=True, verbose_name='Телефон'),
        ),
    ]
