# Generated by Django 4.2.3 on 2023-07-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textlist', '0005_alter_customer_photo_cust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='photo_cust',
        ),
    ]
